### ISSUE TITLE
Bad Request: group chat was upgraded to a supergroup chat

### ISSUE THREAD

**Issue by bacca87** [DoogeJ/properdicebot#1]
Your telegram bot is broken, is not responding to any command.

**Comment by NoxiousPluK** [comment]
Hey thanks! Should be back up now. Looks like it can't handle group upgrades well:

```
Unhandled exception. Telegram.Bot.Exceptions.ApiRequestException: Bad Request: group chat was upgraded to a supergroup chat
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at ProperDiceBot.Program.ProperDiceBot_OnMessage(Object sender, MessageEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
